### ISSUE TITLE
Windows font installation

### ISSUE THREAD

**Issue by JoostvanPinxten** [Caster/Beamer-TUe#5]
It would be nice to have (a link to) a slightly more elaborate explanation of how to install the fonts under windows.

I've managed to find out how it works by following the instructions in the accepted answer here (for Miktex): http://tex.stackexchange.com/questions/95452/how-to-install-a-font-in-windows

**Comment by Caster** [comment]
Thanks a lot for the heads up, I thought that the instructions were clear/working because of a remark in some other issue, but apparently not. Just to be clear, you followed the instructions in [this answer](http://tex.stackexchange.com/a/95456/23145) step by step precisely as described there and that worked? In that case, I'll link to that answer and possibly copy the steps in the README, just in case TeX.SE is down somehow.

**Comment by JoostvanPinxten** [comment]
Yes, that is exactly what I've followed; instead of c:\localtexmf i've used a different folder, and replacing frutiger by tue makes it work as expected. It's a little more elaborate than the Unix/Mac version though ;-)

Thanks for this template by the way. It's the third template that I've tried, and after adding the fonts, it's the only one that really works properly :-)

**Comment by Caster** [comment]
There, as you can see, I updated the README. Thanks a lot again for the input.

Very good to hear that you like the template and that it actually works. If ever you run into a problem again, or you would like some feature to be added, do not hesitate to open an issue again - or even a pull request :-)
